on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          working-directory: wasm
      - uses: actions-rs/toolchain@v1
        with:
          working-directory: wasm
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          working-directory: wasm
          command: check

  fmt:
    name: Rustfmt
    defaults:
      run:
        working-directory: wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          working-directory: wasm
      - uses: actions-rs/toolchain@v1
        with:
          working-directory: wasm
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          working-directory: wasm
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    defaults:
      run:
        working-directory: wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          working-directory: wasm
      - uses: actions-rs/toolchain@v1
        with:
          working-directory: wasm
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          working-directory: wasm
          command: clippy
          args: -- -D warnings
